
<script src="http://www.uni-goettingen.de/js/dw_cookies.js" type="text/javascript"></script>
<script src="http://www.uni-goettingen.de/js/dw_sizerdx.js" type="text/javascript"></script>
<script type="text/javascript">
	var aktuelle_section = "fak_kategorie_2";
	dw_fontSizerDX.setDefaults( "px", 12, 9, 19, ['body', 'td', 'div', 'p', 'font', 'a'] );
	dw_fontSizerDX.set(15, 15, 15, ['ul#navigation li a'] );
	dw_fontSizerDX.set(20, 20, 20, ['div#header_name a'] );
	dw_fontSizerDX.set(11, 11, 11, ['font.seite'] );
	dw_fontSizerDX.set(11, 11, 11, ['ul#pfad li a'] );
	dw_fontSizerDX.set(11, 11, 11, ['a.suchlink'] );
	dw_fontSizerDX.set(16, 16, 16, ['font.boxueberschrift'] );
	dw_fontSizerDX.set(11, 11, 11, ['ul.footerlist-left li a'] );
	dw_fontSizerDX.set(11, 11, 11, ['ul.footerlist-right li a'] );
	//addLoadEvent( finalize );
	addLoadEvent( dw_fontSizerDX.init );
</script>

<link href="<? print("$dir");?>/stylesheets/styles.css" rel="stylesheet" type="text/css" id="style_1">
<!--<link href="http://www.uni-goettingen.de/stylesheets/druck.css" rel="stylesheet" title="default" media="print, embossed" type="text/css">-->
